### ISSUE TITLE
Crash when requirement has different case than .dist-info dir

### ISSUE THREAD

**Issue by estyrke** [QuiNovas/lambda-pkg-resources#2]
I have a project which indirectly depends on the rx package. I haven't investigated the details, but in 0.5.0, `setup.py ldist` fails with the following: 

```
installing package mailhook from dist into build/ldist-mailhook
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    setup(
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.eggs/lambda_setuptools-0.5.0-py3.8.egg/lambda_setuptools/ldist.py", line 152, in run
    self._install_dist_package(
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.eggs/lambda_setuptools-0.5.0-py3.8.egg/lambda_setuptools/ldist.py", line 262, in _install_dist_package
    working_set.resolve(
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.eggs/lambda_pkg_resources-0.0.2-py3.8.egg/lambda_pkg_resources/__init__.py", line 119, in resolve
    dist = best[requirement.key] = env.best_match(
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/Users/emilst/Code/lkss/internwebb/mailhook/.eggs/lambda_pkg_resources-0.0.2-py3.8.egg/lambda_pkg_resources/__init__.py", line 216, in fetch_dist
    dist_path = glob(
IndexError: list index out of range
```

Printf-debugging reveals that it tries to glob the string `/Users/emilst/Code/lkss/internwebb/mailhook/build/ldist-mailhook/rx-*.dist-info`, but the directory it is supposed to match is called `build/ldist-mailhook/Rx-1.6.1.dist-info/`.

**Comment by joseph-wortmann** [comment]
Thanks for the heads-up @estyrke!! Always great to hear from people using the package. We should have a fix out either today or in the morning.

**Comment by mathewmoon** [comment]
@estyrke Before I merge and build a new version in pypi can you pull bug/#38 branch and install from source to test on your system? Right now it passes on my machine building a Lambda with "rx" in the requirements.

**Comment by mathewmoon** [comment]
@estyrke Tests pass on my system after patch. Can you test this on your system? The issue you are having is due to the dependency in lambda-setuptools. To test just remove and reinstall lambda_setuptools then build your lambda again.

**Comment by estyrke** [comment]
@mathewmoon Works perfectly, thanks for the quick action!
